# Generated by Django 2.2 on 2019-05-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
