# Generated by Django 2.2 on 2019-05-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190505_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='company_role',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='consumer',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
