# Generated by Django 2.2 on 2019-05-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190505_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='user_image',
            field=models.ImageField(default='http://placehold.it/500x325', upload_to='admin_photo'),
        ),
    ]
