# Generated by Django 2.2 on 2019-05-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_administrator_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_ID',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(default=-1),
        ),
    ]
